# Generated by Django 6.0.1 on 2026-03-03 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gem_type', models.CharField(choices=[('Blue Sapphire', 'Blue Sapphire'), ('Yellow Sapphire', 'Yellow Sapphire'), ('Pink Sapphire', 'Pink Sapphire'), ('Ruby', 'Ruby'), ('Emerald', 'Emerald'), ('Alexandrite', 'Alexandrite'), ("Cat's Eye", "Cat's Eye"), ('Spinels', 'Spinels'), ('Tourmaline', 'Tourmaline'), ('Garnet', 'Garnet'), ('Topaz', 'Topaz'), ('Quartz', 'Quartz'), ('Other', 'Other')], max_length=50)),
                ('weight_carat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shape', models.CharField(choices=[('Oval', 'Oval'), ('Cushion', 'Cushion'), ('Round', 'Round'), ('Emerald Cut', 'Emerald Cut'), ('Pear', 'Pear'), ('Heart', 'Heart'), ('Marquise', 'Marquise'), ('Baguette', 'Baguette'), ('Square', 'Square'), ('Octagon', 'Octagon'), ('Trillion', 'Trillion'), ('Cabochon', 'Cabochon')], max_length=50)),
                ('color', models.CharField(max_length=100)),
                ('origin', models.CharField(choices=[('Ceylon', 'Ceylon (Sri Lanka)'), ('Madagascar', 'Madagascar'), ('Burma', 'Burma'), ('Mozambique', 'Mozambique'), ('Colombia', 'Colombia'), ('Other', 'Other')], default='Ceylon', max_length=100)),
                ('clarity', models.CharField(blank=True, max_length=100, null=True)),
                ('treatment', models.CharField(blank=True, help_text='e.g. Heat-treated, Unheated', max_length=200, null=True)),
                ('dimensions', models.CharField(blank=True, help_text='e.g. 10x8x5 mm', max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('certification', models.CharField(blank=True, help_text='e.g. GIC, GIA, EGL', max_length=200, null=True)),
                ('availability', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GemHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('background_image', models.ImageField(upload_to='gems/hero/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gems/products/')),
                ('alt_text', models.CharField(blank=True, max_length=100, null=True)),
                ('gem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gems.gem')),
            ],
        ),
    ]
