import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useCart } from "../../context/useCart";
export default function InvoiceHeader({ order }) {
    const { getCountrySettings } = useCart();
    const countrySettings = getCountrySettings(order.country?.name);
    return (_jsxs(_Fragment, { children: [_jsx("div", { className: "flex justify-center mb-6", children: _jsx("img", { src: "/logo/JewelryLogo.png", alt: "SPARKLER Logo", className: "h-16" }) }), _jsxs("div", { className: "flex justify-between items-center mb-6", children: [_jsx("h1", { className: "text-4xl font-bold text-[#C9A24D]", children: "Invoice" }), _jsx("span", { className: `px-4 py-1 rounded-full text-xs font-semibold tracking-wide ${order.status === "PAID"
                            ? "bg-green-500/20 text-green-400"
                            : "bg-red-500/20 text-red-400"}`, children: order.status })] }), _jsxs("div", { className: "text-sm text-[#BDBDBD] space-y-1 mb-8", children: [_jsxs("p", { children: [_jsx("span", { className: "text-white font-semibold", children: "Invoice #:" }), " ", order.order_id] }), _jsxs("p", { children: [_jsx("span", { className: "text-white font-semibold", children: "Date:" }), " ", new Date(order.created_at).toLocaleDateString()] }), _jsxs("p", { children: [_jsx("span", { className: "text-white font-semibold", children: "Country:" }), " ", order.country?.name ?? "N/A"] }), _jsxs("p", { children: [_jsx("span", { className: "text-white font-semibold", children: "Subtotal:" }), " $", order.subtotal.toFixed(2)] }), _jsxs("p", { children: [_jsx("span", { className: "text-white font-semibold", children: "Shipping:" }), " $", countrySettings.shipping_cost.toFixed(2)] }), _jsxs("p", { children: [_jsx("span", { className: "text-white font-semibold", children: "Tax:" }), " $", order.tax.toFixed(2)] }), _jsxs("p", { children: [_jsx("span", { className: "text-white font-semibold", children: "VAT:" }), " $", order.vat.toFixed(2)] }), _jsxs("p", { className: "text-white font-semibold text-lg", children: ["Total: $", order.total.toFixed(2)] })] }), _jsx("div", { className: "my-6 border-t border-[#C9A24D]/30" })] }));
}
