"use client";
import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from "react";
import Modal from "../ui/Modal";
import { FaUser, FaMapMarkerAlt, FaLock } from "react-icons/fa";
import toast from "react-hot-toast";
import EditProfileModal from "./EditProfileModal";
import ChangePasswordModal from "./ChangePasswordModal";
export default function AccountSettingsModal({ isOpen, onClose }) {
    const [showEditProfile, setShowEditProfile] = useState(false);
    const [showChangePassword, setShowChangePassword] = useState(false);
    const handleManageAddresses = () => {
        toast("Address management coming next 👀");
    };
    return (_jsxs(_Fragment, { children: [_jsx(Modal, { isOpen: isOpen, onClose: onClose, title: "Account Settings", children: _jsxs("div", { className: "space-y-6 text-[#EDEDED]", children: [_jsxs("div", { className: "flex items-center p-4 bg-[#1F1F1F] rounded-2xl border border-[#C9A24D]/30 shadow-md hover:shadow-lg transition", children: [_jsx("div", { className: "w-12 h-12 flex items-center justify-center bg-[#C9A24D] text-[#1A1A1A] rounded-full text-xl mr-4", children: _jsx(FaUser, {}) }), _jsxs("div", { className: "flex-1", children: [_jsx("h3", { className: "font-semibold text-[#C9A24D] text-lg", children: "Edit Profile" }), _jsx("p", { className: "text-[#BDBDBD] text-sm", children: "Update your personal information and contact details." })] }), _jsx("button", { onClick: () => setShowEditProfile(true), className: "px-4 py-2 bg-[#C9A24D] hover:bg-[#B08B3E] text-[#1A1A1A] rounded-lg font-medium transition", children: "Edit" })] }), _jsxs("div", { className: "flex items-center p-4 bg-[#1F1F1F] rounded-2xl border border-[#C9A24D]/30 shadow-md hover:shadow-lg transition", children: [_jsx("div", { className: "w-12 h-12 flex items-center justify-center bg-[#C9A24D] text-[#1A1A1A] rounded-full text-xl mr-4", children: _jsx(FaMapMarkerAlt, {}) }), _jsxs("div", { className: "flex-1", children: [_jsx("h3", { className: "font-semibold text-[#C9A24D] text-lg", children: "Manage Addresses" }), _jsx("p", { className: "text-[#BDBDBD] text-sm", children: "Add, edit, or remove delivery addresses." })] }), _jsx("button", { onClick: handleManageAddresses, className: "px-4 py-2 bg-[#C9A24D] hover:bg-[#B08B3E] text-[#1A1A1A] rounded-lg font-medium transition", children: "Edit" })] }), _jsxs("div", { className: "flex items-center p-4 bg-[#1F1F1F] rounded-2xl border border-[#C9A24D]/30 shadow-md hover:shadow-lg transition", children: [_jsx("div", { className: "w-12 h-12 flex items-center justify-center bg-[#C9A24D] text-[#1A1A1A] rounded-full text-xl mr-4", children: _jsx(FaLock, {}) }), _jsxs("div", { className: "flex-1", children: [_jsx("h3", { className: "font-semibold text-[#C9A24D] text-lg", children: "Change Password" }), _jsx("p", { className: "text-[#BDBDBD] text-sm", children: "Secure your account with a strong password." })] }), _jsx("button", { onClick: () => setShowChangePassword(true), className: "px-4 py-2 bg-[#C9A24D] hover:bg-[#B08B3E] text-[#1A1A1A] rounded-lg font-medium transition", children: "Change" })] }), _jsx("div", { className: "flex justify-end", children: _jsx("button", { onClick: onClose, className: "px-6 py-2 bg-[#C9A24D] hover:bg-[#B08B3E] text-[#1A1A1A] rounded-lg font-semibold transition", children: "Close" }) })] }) }), _jsx(EditProfileModal, { isOpen: showEditProfile, onClose: () => setShowEditProfile(false) }), _jsx(ChangePasswordModal, { isOpen: showChangePassword, onClose: () => setShowChangePassword(false) })] }));
}
