# Generated by Django 6.0.6 on 2026-07-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('cod', 'Cash on Delivery')], default='card', max_length=20),
        ),
    ]
