# Generated by Django 6.0.1 on 2026-02-02 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='auction_items/')),
                ('description', models.TextField()),
                ('min_bid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_bid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('duration', models.IntegerField(help_text='Auction duration in seconds')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='auction_backgrounds/')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('auction_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.auctionitem')),
            ],
        ),
    ]
