# Generated by Django 6.0.1 on 2026-02-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_bid_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='bid_increment',
            field=models.DecimalField(decimal_places=2, default=500, help_text='The allowed bid increment for this item', max_digits=12),
        ),
    ]
