# Generated by Django 6.0.1 on 2026-02-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auctionitem_bid_increment'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='bid_increment',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=12),
        ),
    ]
