# Generated by Django 6.0.1 on 2026-02-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auctionitem_end_time_alter_auctionitem_bid_increment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionPageBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='auction_page_background/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='auctionitem',
            name='background_image',
        ),
    ]
