# Generated by Django 6.0.2 on 2026-03-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auctionpagebackground_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='max_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
