# Generated by Django 6.0.6 on 2026-09-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Set whether this bid is open/active'),
        ),
    ]
