# Generated by Django 6.0.1 on 2026-01-19 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gem', models.CharField(choices=[('Sapphire', 'Sapphire'), ('Ruby', 'Ruby'), ('Emerald', 'Emerald'), ('Diamond', 'Diamond')], max_length=50)),
                ('carat', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('metal', models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Platinum', 'Platinum')], max_length=50)),
                ('certification', models.BooleanField(default=True)),
                ('availability', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('alt_text', models.CharField(blank=True, max_length=100, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product')),
            ],
        ),
    ]
