# Generated by Django 6.0.1 on 2026-01-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='video_url',
        ),
        migrations.AddField(
            model_name='service',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='service_videos/'),
        ),
    ]
