# Generated by Django 6.0.1 on 2026-01-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_service_video_url_service_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField()),
                ('background_image', models.ImageField(upload_to='hero/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(choices=[('wrench', 'Wrench'), ('diamond', 'Diamond'), ('watch', 'Watch'), ('zap', 'Zap'), ('edit', 'Edit')], default='wrench', max_length=20),
        ),
    ]
