# Generated by Django 6.0.1 on 2026-01-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contacthero_alter_contactinfo_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacthero',
            name='map_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
