# Generated by Django 6.0.1 on 2026-01-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallink',
            name='icon_class',
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='name',
            field=models.CharField(choices=[(1, 'Instagram'), (2, 'Facebook'), (3, 'LinkedIn'), (4, 'YouTube'), (5, 'TikTok')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
