# Generated by Django 6.0.1 on 2026-01-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0002_remove_sociallink_icon_class_alter_sociallink_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='name',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('tiktok', 'TikTok')], max_length=20, unique=True),
        ),
    ]
