# Generated by Django 6.0.1 on 2026-01-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('gem', models.CharField(choices=[('diamond', 'Diamond'), ('ruby', 'Ruby'), ('emerald', 'Emerald'), ('sapphire', 'Sapphire'), ('gold', 'Gold')], max_length=50)),
                ('metal', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('platinum', 'Platinum')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carat', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('availability', models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock')], default='in_stock', max_length=20)),
                ('image_main', models.ImageField(upload_to='products/')),
                ('image_secondary', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
