# Generated by Django 6.0.1 on 2026-01-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_sets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gem',
            field=models.CharField(choices=[('diamond', 'Diamond'), ('ruby', 'Ruby'), ('emerald', 'Emerald'), ('sapphire', 'Sapphire')], max_length=50),
        ),
    ]
