# Generated by Django 6.0.1 on 2026-01-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_sets', '0003_remove_product_hero_image_alter_product_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageHeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional title for the hero section', max_length=255)),
                ('subtitle', models.TextField(blank=True, help_text='Optional subtitle for the hero section')),
                ('background_image', models.ImageField(upload_to='hero/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='HeroImage',
        ),
    ]
