# Generated by Django 6.0.1 on 2026-01-20 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customjewelrycta',
            name='cta_link',
        ),
        migrations.RemoveField(
            model_name='customjewelrycta',
            name='cta_text',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='primary_cta_link',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='primary_cta_text',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='secondary_cta_link',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='secondary_cta_text',
        ),
    ]
