# Generated by Django 6.0.1 on 2026-01-23 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_customjewelrycta_cta_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='link',
        ),
    ]
